# Generated by Django 4.1.3 on 2022-12-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hospitality_courses_profile_tourism_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_courses',
            name='link',
            field=models.URLField(default='https://www.youtube.com/playlist?list=PLIfNzIyhq0S1vR3gRtjvScKDsEy6V_eDq'),
            preserve_default=False,
        ),
    ]
