# Generated by Django 4.1.3 on 2022-12-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_travel_courses_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitality_courses',
            name='link',
            field=models.URLField(default='https://www.youtube.com/playlist?list=PLIfNzIyhq0S1vR3gRtjvScKDsEy6V_eDq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourism_courses',
            name='link',
            field=models.URLField(default='https://www.youtube.com/playlist?list=PLIfNzIyhq0S1vR3gRtjvScKDsEy6V_eDq'),
            preserve_default=False,
        ),
    ]
