# Generated by Django 4.1.3 on 2022-12-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hospitality_courses_link_tourism_courses_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='hotelimages')),
                ('name', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=5)),
                ('book', models.BooleanField(default=False)),
            ],
        ),
    ]
