# Generated by Django 4.1.7 on 2023-08-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hotels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
